### ISSUE TITLE
Katex 并不支持所有的数学公式表达，您有更好的preview plug-in推荐吗？

### ISSUE THREAD

**Issue by singledoggy** [cold-soda-jay/Markdown-vim#1]
如果需要自己open 浏览器转用其他的渲染方式我就放弃vim+markdown只把vim当作latex工具了，事实上typora对公式的渲染支持度也比您推荐的那个plug好...

**Comment by cold-soda-jay** [comment]
暂时没有，我在使用中没有遇到过类似问题，所以不太清楚。你可以去iamcco/markdown-preview.nvim下提出issue 😄
