### ISSUE TITLE
context math()的内容好像失效了

### ISSUE THREAD

**Issue by pipiTan** [cold-soda-jay/Markdown-vim#5]
mk dm这些能用，其他的都不能用。

**Comment by cold-soda-jay** [comment]
我这边试了下没有问题啊，你的配置是什么？
我刚刚重新更新了下snippet，你试试行不行？

**Comment by pipiTan** [comment]
你好 我用的是spacevim 我刚刚重新下载了你的文件 还是不行 你看看我的截图
https://ftp.bmp.ovh/imgs/2021/04/250e3e4338b7a150.gif
https://ftp.bmp.ovh/imgs/2021/04/f028a9e6f7f65dbc.gif

**Comment by cold-soda-jay** [comment]
懂了。因为Context math()是根据syntax 来判断某个区域是否是math的区域，所以如果syntax没开的话可能会不行。另外还需要把markdown相关的插件也安装好，比如plasticboy/vim-markdown。你可以检查下有没有装上

**Comment by cold-soda-jay** [comment]
你可以把光标移动到math区域，然后输入
```:echo(eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))"))```
记下来出现的数字，然后输入
```:echo(synIDattr(数字,"name"))```
看下输出的区域标示有没有在.snippet 文件的那个texMathZones表里，如果没有的话你可能得装下vim-markdown，最好再装个lervag/vimtex

**Comment by pipiTan** [comment]
:echo(eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")) 输出[]
而且 我vim-markdown vimtex都装了 还是不行
syntax是怎么开启的啊

**Comment by cold-soda-jay** [comment]
你试试 ```:syntax on```， 我试了下，不开启的话确实会出现空的列表

**Comment by pipiTan** [comment]
不知道问题出在哪 还是不行

**Comment by cold-soda-jay** [comment]
hmm，那可能是spacevim的问题？你可以换成neovim试试？
或者你可以直接把 context math() 删了。记得看下math部分的snippet，删掉些不常用的，改改有冲突的，其实也能用
context math() 主要是避免关键词冲突的

**Comment by pipiTan** [comment]
我把vim_markdown_math设置之后可以正常使用了
但是遇到了新问题  
在输入mk dm之后$$符号会自动隐藏 不能像图片那样在光标所在行就显示$$符号 应该要怎么设置呢

**Comment by cold-soda-jay** [comment]
这个应该是vim-markdown 里面可以设置的，你可以看下docu

**Comment by draftman9** [comment]
> 懂了。因为Context math()是根据syntax 来判断某个区域是否是math的区域，所以如果syntax没开的话可能会不行。另外还需要把markdown相关的插件也安装好，比如plasticboy/vim-markdown。你可以检查下有没有装上

snips为什么会跟该插件有关？我一直以为这个没必要的。还有 markdown.snippets 中的 “nomath” 是什么意思？😓搞了两天我才找到这里。不过相关snips是真好用👍！
